import { motion } from 'framer-motion';
const fade={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true},transition:{duration:.6}};
const cards=(items:string[])=>items;
function Section({id,kicker,title,children}:{id:string;kicker:string;title:string;children:any}){return <section id={id} className='max-w-6xl mx-auto px-6 py-24'><motion.p {...fade} className='uppercase tracking-[0.25em] text-xs text-slate-500'>{kicker}</motion.p><motion.h2 {...fade} className='mt-3 text-4xl md:text-6xl font-semibold tracking-tight'>{title}</motion.h2><div className='mt-12'>{children}</div></section>}
function Card({title,text}:{title:string;text:string}){return <motion.div {...fade} whileHover={{y:-6}} className='rounded-3xl bg-white border border-slate-200 p-8 shadow-sm hover:shadow-xl transition'><h3 className='text-2xl font-semibold'>{title}</h3><p className='mt-4 text-slate-600 leading-8'>{text}</p></motion.div>}
export default function App(){return <main className='bg-slate-50 text-slate-900'>
<header className='fixed top-0 inset-x-0 z-50'><div className='max-w-6xl mx-auto px-6 pt-5'><div className='h-16 rounded-full bg-white/85 backdrop-blur border border-slate-200 shadow-sm px-6 flex items-center justify-between'><span className='font-semibold'>Yves David</span><nav className='hidden md:flex gap-8 text-sm text-slate-600'><a href='#services'>Services</a><a href='#projets'>Projets</a><a href='#tarifs'>Tarifs</a><a href='#contact'>Contact</a></nav></div></div></header>
<section className='max-w-6xl mx-auto px-6 pt-40 pb-24 grid md:grid-cols-2 gap-12 items-center'>
<motion.div {...fade}><p className='uppercase tracking-[0.25em] text-xs text-slate-500'>Développeur Web Freelance</p><h1 className='mt-4 text-5xl md:text-8xl leading-[0.92] font-semibold tracking-tight'>Je crée des sites web qui inspirent confiance.</h1><p className='mt-8 text-lg text-slate-600 leading-8 max-w-xl'>Sites vitrines premium, interfaces modernes et projets sur mesure conçus pour valoriser votre image et convertir vos visiteurs.</p><div className='mt-10 flex gap-4 flex-wrap'><a href='#contact' className='px-7 py-4 rounded-full bg-slate-900 text-white'>Démarrer un projet</a><a href='#projets' className='px-7 py-4 rounded-full border border-slate-300 bg-white'>Voir mes réalisations</a></div></motion.div>
<motion.div {...fade} className='rounded-[36px] h-[520px] bg-gradient-to-br from-slate-900 via-slate-800 to-slate-700 shadow-2xl'/>
</section>
<Section id='services' kicker='Services' title='Des solutions claires et efficaces.'><div className='grid md:grid-cols-3 gap-6'><Card title='Site vitrine' text='Présentez votre activité avec un site moderne, rapide et crédible.'/><Card title='Application web' text='Dashboard, espace membre, outil interne ou automatisation métier.'/><Card title='Refonte' text='Modernisez un site existant avec un design plus premium.'/></div></Section>
<Section id='projets' kicker='Portfolio' title='Quelques projets.'><div className='grid md:grid-cols-3 gap-6'><Card title='Plateforme d’entraide' text='Mise en relation simple entre besoins et solutions.'/><Card title='Messagerie temps réel' text='Chat moderne avec salons privés et échanges instantanés.'/><Card title='Application sport' text='Suivi des performances, séances et progression.'/></div></Section>
<Section id='process' kicker='Méthode' title='Un process simple.'><div className='grid md:grid-cols-4 gap-6'><Card title='1. Échange' text='On définit votre besoin et vos objectifs.'/><Card title='2. Design' text='Maquette claire et structure optimisée.'/><Card title='3. Développement' text='Intégration rapide et propre.'/><Card title='4. Mise en ligne' text='Publication et ajustements finaux.'/></div></Section>
<Section id='tarifs' kicker='Tarifs' title='Des offres lisibles.'><div className='grid md:grid-cols-3 gap-6'><Card title='Starter • 250€' text='Une page premium, responsive, mise en ligne.'/><Card title='Business • 600€' text='Trois pages, animations légères, SEO de base.'/><Card title='Sur mesure • Devis' text='Projet spécifique selon vos besoins.'/></div></Section>
<section id='contact' className='max-w-6xl mx-auto px-6 py-24'><div className='rounded-[36px] bg-slate-900 text-white p-10 md:p-16'><p className='uppercase tracking-[0.25em] text-xs text-slate-400'>Contact</p><h2 className='mt-4 text-4xl md:text-6xl font-semibold tracking-tight'>Parlons de votre projet.</h2><p className='mt-6 text-slate-300 max-w-2xl text-lg leading-8'>Vous avez une idée ou besoin d’un site professionnel ? Contactez-moi.</p><a href='mailto:contact@email.com' className='inline-block mt-8 px-7 py-4 rounded-full bg-white text-slate-900'>Me contacter</a></div></section>
<footer className='max-w-6xl mx-auto px-6 py-12 text-slate-500'>© 2026 Yves David</footer></main>}
